# A webscraper that searches through the passing leaders in the current NFL season and sorts by passing attempts.

from bs4 import BeautifulSoup
import re
import urllib
import requests

input_file = open("PassingYards.txt", "w")
URL = 'https://www.pro-football-reference.com/years/2019/passing.htm'
page = requests.get(URL)

soup = BeautifulSoup(page.content, 'html.parser')
data = []
htmltable = soup.find('div', class_ = 'overthrow table_container')

table_body = htmltable.find('tbody')

rows = table_body.find_all('tr')

for row in rows:
    cols = row.find_all('td') or row.find_all('th')
    cols = [ele.text.strip() for ele in cols]
    data.append([ele for ele in cols if ele]) # Get rid of empty values


input_file.write("Generated by PassingYards.py\n\n")
input_file.write("Top 50 2019 NFL Passers by Attempts\n")
input_file.write("An asterisk denotes a Pro Bowl.\n\n")
# print("")
for x in range(0,50):
    if data[x][0] == 'Rk':
        del(data[x])
    else:
        input_file.write(str(x+1) + " " + data[x][0] + " " + data[x][7] + "/" + data[x][8] + " "  + data[x][10] + " Passing Yards " + data[x][11] + " TDs " + data[x][13] + " INTs\n")


